/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'echo' at '6/10/18 6:23 PM' with Gradle 2.10
 *
 * @author echo, @date 6/10/18 6:23 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
